### ISSUE TITLE
SDK crashes when the response body is empty

### ISSUE THREAD

**Issue by itsrachelfish** [wetfish/login#4]
This bug ended up crashing NickServ:

```
TypeError: Cannot read property 'body' of undefined
    at Request._callback (/home/services/services/login/sdk/server/wetfish-login.js:34:44)
    at self.callback (/home/services/services/login/node_modules/request/request.js:344:22)
    at Request.emit (events.js:95:17)
    at Request.onRequestError (/home/services/services/login/node_modules/request/request.js:961:8)
    at ClientRequest.emit (events.js:95:17)
    at CleartextStream.socketErrorListener (http.js:1548:9)
    at CleartextStream.emit (events.js:95:17)
    at Socket.onerror (tls.js:1456:17)
    at Socket.emit (events.js:117:20)
    at net.js:441:14
```

**Comment by itsrachelfish** [comment]
Fixed in new repo: https://github.com/wetfish/login-sdk
